version: "3.4"
services:
  beacon_node:
    build:
      context: ../
      dockerfile: docker/from_source.Dockerfile
    network_mode: host
    volumes:
      - ./:/amphora
      - beacon_node:/data
      - logs:/logs
    # ports:
    #  - "9000:9000" # P2P port
    #  - "9596:9596" # REST API port
    command: >
      beacon
        --rcConfig /amphora/rcconfig.yml
        --rootDir /data
        --logFile /logs/beacon.log
    # NodeJS applications have a default memory limit of 2.5GB.
    # This limit is bit tight for a Prater node, it is recommended to raise the limit
    # since memory may spike during certain network conditions.
    environment:
      NODE_OPTIONS: --max_old_space_size=6144
      LODESTAR_PRESET: minimal

  geth:
    build: ./geth
    network_mode: host
    volumes:
      - geth:/data

volumes:
  beacon_node:
  logs:
  geth:
