version: "3.4"

# Configuration to work with a local non-dockerized Lodestar node on MacOS
# For local testing and quick debugging
#
# HOW TO USE: Start a Lodestar node, then run
#
# docker-compose -f docker/docker-compose.local.mac.yml up -d

services:
  prometheus:
    build:
      context: prometheus
      args:
        config_file: prometheus.local.yml
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - "prometheus:/prometheus"

  grafana:
    build:
      context: grafana
      args:
        DATASOURCE_FILE: datasource.local.yml
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "grafana:/var/lib/grafana"
    depends_on: [prometheus]

volumes:
  prometheus:
  grafana:
