name: Sim merge tests

on:
  push:
    branches:
      - stable
      - unstable
  pull_request:
    branches:
      - stable
      - unstable

env:
  GETH_COMMIT: be9742721f56eb8bb7ebf4f6a03fb01b13a05408
  NETHERMIND_COMMIT: 82f331a3e7ff21712a5f839e0a62ba7c16110e44

jobs:
  sim-merge-tests:
    name: Sim merge tests
    runs-on: ubuntu-latest
    steps:
      # <common-build> - Uses YAML anchors in the future
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/gallium"
      - name: Node.js version
        id: node
        run: echo "::set-output name=v8CppApiVersion::$(node --print "process.versions.modules")"
      - name: Restore dependencies
        uses: actions/cache@master
        id: cache-deps
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-${{ steps.node.outputs.v8CppApiVersion }}-${{ hashFiles('**/yarn.lock', '**/package.json') }}
      - name: Install & build
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --ignore-optional && yarn build
      - name: Build
        run: yarn build
        if: steps.cache-deps.outputs.cache-hit == 'true'
      # </common-build>

      # Install Geth merge interop
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Clone Geth merge interop branch
        run: git clone -b master https://github.com/g11tech/go-ethereum.git && cd go-ethereum && git reset --hard $GETH_COMMIT && git submodule update --init --recursive
      - name: Build Geth
        run: cd go-ethereum && make

      - name: Test Lodestar <> Geth interop
        run: yarn test:sim:merge-interop
        working-directory: packages/beacon-node
        env:
          EL_BINARY_DIR: ../../go-ethereum/build/bin
          EL_SCRIPT_DIR: kiln/geth
          ENGINE_PORT: 8551
          ETH_PORT: 8545
          TX_SCENARIOS: simple

      # Install Nethermind merge interop
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      - name: Clone Nethermind merge interop branch
        run: git clone -b kiln-rebased https://github.com/g11tech/nethermind --recursive && cd nethermind && git reset --hard $NETHERMIND_COMMIT && git submodule update --init --recursive
      - name: Build Nethermind
        run: cd nethermind/src/Nethermind && dotnet build Nethermind.sln -c Release

      - name: Test Lodestar <> Nethermind interop
        run: yarn test:sim:merge-interop
        working-directory: packages/beacon-node
        env:
          EL_BINARY_DIR: ../../nethermind/src/Nethermind/Nethermind.Runner
          EL_SCRIPT_DIR: kiln/nethermind
          ENGINE_PORT: 8551
          ETH_PORT: 8545

      - name: Upload debug log test files
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: debug-test-logs
          path: packages/beacon-node/test-logs
